apiVersion: apps/v1
kind: Deployment
metadata:
    name: infer
    labels:
        app: api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api
    template:
        metadata:
            labels:
                app: api
        spec:
            containers:
                - name: infer
                  image: aka7919/infer
                  command: ["python3", "main.py"]
                  ports:
                      - containerPort: 5000
                  volumeMounts:
                  - name: model
                    mountPath: /mnt
            volumes:
              - name: model
                persistentVolumeClaim:
                  claimName: kctl-vpc2

---
apiVersion: v1
kind: Service
metadata:
    name: infer-end
spec:
    type: LoadBalancer
    selector:
        app: api
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000